# Site settings
title: Mark Steve Samson
email: hello@marksteve.com
description: A guy in the internet
baseurl: ""
url: "https://marksteve.com"
twitter_username: themarksteve
github_username: marksteve
exclude:
  - CNAME
  - package.json
  - node_modules/
  - bundle/
  - .bundle/
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown
